# cargo make --profile production task
[tasks.env_check]
dependencies = ["echo_env"]
condition = { env_set = [ "BUILD_FLAG", "RUST_COMPILE_TARGET", "CRATE_TYPE", "TARGET_OS"],  channels = ["nightly"] }

[tasks.flowy-sdk-dev]
description = "Build flowy sdk in dev mode"
category = "Build"
dependencies = ["env_check"]
run_task = { name = ["setup-crate-type","sdk-dev-build", "post-desktop", "restore-crate-type", "copy-to-sys-tmpdir"] }

[tasks.sdk-dev-build]
script = [
  """
    cd rust-lib/
    cargo build --package=dart-ffi --target ${RUST_COMPILE_TARGET} --features=${FEATURES}
    cd ../
  """,
]
script_runner = "@shell"

[tasks.flowy-sdk-release]
description = "Build flowy sdk in release mode"
category = "Build"
dependencies = ["env_check"]
run_task = { name = ["setup-crate-type","sdk-release-build", "post-desktop", "restore-crate-type"] }


[tasks.sdk-release-build]
script = [
  """
    cd rust-lib/
    cargo build --${BUILD_FLAG} --package=dart-ffi --target ${RUST_COMPILE_TARGET} --features=${FEATURES}
    cd ../
  """,
]
script_runner = "@shell"


[tasks.post-desktop]
private = true
script = [
  """
    echo "ðŸš€ ðŸš€ ðŸš€  Flowy-SDK build success"
    cp ${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}/rust-lib/target/${RUST_COMPILE_TARGET}/${BUILD_FLAG}/lib${CARGO_MAKE_CRATE_FS_NAME}.${SDK_EXT} \
    ${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}/app_flowy/packages/flowy_sdk/macos/lib${CARGO_MAKE_CRATE_FS_NAME}.${SDK_EXT}
  """,
  """
    cp ${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}/rust-lib/${CARGO_MAKE_CRATE_NAME}/binding.h \
    ${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}/app_flowy/packages/flowy_sdk/macos/Classes/binding.h
  """,
]
script_runner = "@duckscript"

[tasks.copy-to-sys-tmpdir]
private = true
condition = { profiles = [ "development-mac" ], platforms = ["mac"] }
script = [
  """
  # post the dylib target_path that use for flutter unit test
  target_path = set ${TMPDIR}/appflowy_client/lib${CARGO_MAKE_CRATE_FS_NAME}.${SDK_EXT}
    rm ${target_path}
    cp ${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}/rust-lib/target/${RUST_COMPILE_TARGET}/${BUILD_FLAG}/lib${CARGO_MAKE_CRATE_FS_NAME}.${SDK_EXT} ${target_path}
  """,
]
script_runner = "@duckscript"

